modified to avoid rerun of gadget script at shutdown
Signed-off-by: Lalith Panditharatne <Lalith@access-is.com>

diff --git a/support/scripts/configure-rootfs b/support/scripts/configure-rootfs
--- a/support/scripts/configure-rootfs
+++ b/support/scripts/configure-rootfs
@@ -48,35 +48,45 @@ EOF
 chmod +x output/target/root/gadget
 
 cat > output/target/etc/init.d/S01mount <<EOF
-#!/bin/sh
-if [ -b "/dev/mtdblock4" ];then 
-	mkdir /.base; 
-	mount -t jffs2 /dev/mtdblock4 /.base ;
-	[ -d /.base/ovl ] || mkdir /.base/ovl ;
-	[ -d /.base/persist ] || mkdir /.base/persist ;
-fi
-if [ -f /.base/ovl/mach.squash ]; then
-	if [ -f /.base/ovl/MD5SUM ]; then
-		if  md5sum -s -c /.base/ovl/MD5SUM  ; then
-			echo -n "Creating machine overlay .. "
-			mkdir /.lower /.upper /.tmp /petram;
-			mount /.base/ovl/mach.squash /.lower;
-			mount -t overlay -o lowerdir=/.lower,upperdir=/.upper,workdir=/.tmp  overlay /petram;
-			echo "done";
+#
+# Configure machine
+#
+case"\$1" in
+	start)
+		echo "Configuring machine..."
+		if [ -b "/dev/mtdblock4" ];then 
+			mkdir /.base; 
+			mount -t jffs2 /dev/mtdblock4 /.base ;
+			[ -d /.base/ovl ] || mkdir /.base/ovl ;
+			[ -d /.base/persist ] || mkdir /.base/persist ;
+		fi
+		if [ -f /.base/ovl/mach.squash ]; then
+			if [ -f /.base/ovl/MD5SUM ]; then
+				if  md5sum -s -c /.base/ovl/MD5SUM  ; then
+					echo -n "Creating machine overlay .. "
+					mkdir /.lower /.upper /.tmp /petram;
+					mount /.base/ovl/mach.squash /.lower;
+					mount -t overlay -o lowerdir=/.lower,upperdir=/.upper,workdir=/.tmp  overlay /petram;
+					echo "done";
+				else
+					echo "mach.squash checksum failed, not mounting overlay";
+					/root/gadget;
+				fi
+			else
+				echo "mach.squash present but MD5SUM file not found";
+				/root/gadget;
+			fi
+			
 		else
-			echo "mach.squash checksum failed, not mounting overlay";
+			echo "Unconfigured system, starting usb gadgets";
 			/root/gadget;
 		fi
-	else
-		echo "mach.squash present but MD5SUM file not found";
-		/root/gadget;
-	fi
+		;;
 	
-else
-	echo "Unconfigured system, starting usb gadgets";
-	/root/gadget;
-fi
-exit 0
+	stop)
+		;;
+esac
+exit \$?
 EOF
 
 chmod +x output/target/etc/init.d/S01mount
