added uuc /enable / disable bits
Signed-off-by: Lalith Panditharatne <Lalith@access-is.com>

diff --git a/package/freescale-imx/imx-uuc/S80imx-uuc b/package/freescale-imx/imx-uuc/S80imx-uuc
--- a/package/freescale-imx/imx-uuc/S80imx-uuc
+++ b/package/freescale-imx/imx-uuc/S80imx-uuc
@@ -5,9 +5,11 @@ DAEMON=/usr/bin/$NAME
 
 case "$1" in
     start)
-	printf "Starting $NAME: "
-	start-stop-daemon -S -q -b -m -p /var/run/${NAME}.pid -x $DAEMON
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+    if grep -q daemon=yes /etc/default/uuc ; then
+        printf "Starting $NAME: "
+        start-stop-daemon -S -q -b -m -p /var/run/${NAME}.pid -x $DAEMON
+        [ $? = 0 ] && echo "OK" || echo "FAIL"
+    fi
 	;;
     stop)
 	printf "Stopping $NAME: "
